name = "Tasman Dynamics - Interaction Framework"
prefix = "tasdyn"
author = "Tasman Dynamics"
description = "A highly-advanced, standalone clickable cockpit framework for Arma 3."
main_prefix = "z"

[version]
major = 1
minor = 0
patch = 0

[key]
name = "tasdyn_framework"